### ISSUE TITLE
context data on which steps can add data for other steps

### ISSUE THREAD

**Issue by learner010** [pytest-dev/pytest-bdd#140]
How can one add a context data, which can be passed around steps, so that the steps can access it and make changes to it.

I tried something like below:

```python
@given('blah')
def context():
    return {}

@when('blah blah')
def make_changes_to_context(context):
    context['new_key'] = 'new data'
    return context

@then('blah blah blah')
def check_stuff(context):
    assert context['new_key'] == 'new data'
```

Raises `Key Error`, the `context` at `check_stuff` is not being updated by `make_changes_to_context` function.

Is there any other way I could pass context among step functions?

**Comment by olegpidsadnyi** [comment]
It should be fine. Could you submit a PR with the test that is faling?

**Comment by learner010** [comment]
At blah.feature

```cucumber
Feature: Blah

Scenario: Lets Blah
    Given blah
    When blah blah
    Then blah blah blah
```

At test_blah.py

```python
from pytest_bdd import scenario, given, when, then, parsers

@scenario('../features/composer.feature', 'Lets Blah')
def test_single_function_composer():
    pass

@given('blah')
def context():
    return {}

@when('blah blah')
def update_context(context):
    context['config'] = 'hello world'
    return context

@then('blah blah blah')
def test_context(context):
    assert context['config'] == 'hello world'
```

**Comment by olegpidsadnyi** [comment]
OK, I see now what's wrong.
PyTest is treating all funcitons having test_* prefix as a test case. So it runs 2 test cases. Your output is not verbose so maybe you didn't notice the first dot (meaning passed test). It fails on the second test which is test_context, because in this case the update_context wasn't called.

The solution would be to rename test_context to check_context. Starting with meaningful names instead of blah blah could also help not getting this gotcha ;)

Enjoy

**Comment by learner010** [comment]
Thanx, for the reply. So only the scenario can have test_* prefix.
