### ISSUE TITLE
Gherkin file auto completion of available steps 

### ISSUE THREAD

**Issue by TylerDerton** [pytest-dev/pytest-bdd#192]
Hi All,
Pardon silly question as I new to python and this pytest-bdd.
Gherkin file auto completion of available steps seems to be not working for me.
While it did worked on behave.
Any thoughts what it might be.
Thanks

**Comment by The-Compiler** [comment]
What auto completion? Where?

**Comment by TylerDerton** [comment]
When you type scenarios and press Control+ Space available or discovered steps come up as drop down list. Same for all IDE (almost).

**Comment by jangeroo** [comment]
@TylerDerton It sounds like you're talking about a feature of the IDE, not of pytest-bdd. Feature files are feature files, regardless of which test framework you're using to execute them as automated tests. Auto-completion for editing files is not a feature of the test framework.

If your IDE depends on the step definition files in order to autocomplete the steps, this would again not likely be an issue with pytest-bdd (which does have a slightly different format for step definitions that does Behave) but rather with the specific autocompletion functionality in any given IDE that has not been coded to support pytest-bdd's format for step definitions. This is not something that pytest-bdd can control.
