### ISSUE TITLE
Import steps from other modules

### ISSUE THREAD

**Issue by rikirenz** [pytest-dev/pytest-bdd#209]
This is my tree:
```
external_module/
     helpers.py
tests/
    conftest.py
    test_bar.py
    bar.feature
```

I have this natural language test ( `tests/bar.feature` ):
``` Python
Scenario: it is a foo scenario
  Given I am logged in
  [...]
```

I have in test module the following function (`tests/test_bar.py`):
``` Python
from helpers import log_in
@scenario('bar.feature', 'it is a foo scenario')
def test_foo():
    pass
```

And in a external module I have this step function (`external_module/helpers.py`):
``` Python
@given('I am logged in')
def login():
    print('foo')
```

If I try to execute the test but I receive this error:
``` Bash
StepDefinitionNotFoundError: Step definition is not found: Given "I am logged in". Line 249 in scenario "it is a foo scenario" in the feature "/code/tests/bar.feature
```

Do you think there is a way to define a step function in a module that does not contain the `@scenario` function and make the test work?

**Comment by bubenkoff** [comment]
it's possible to have your setup, the only thing you need to do is to import * from helpers module either in `tests/conftest.py` or in `tests/test_bar.py`
I would suggest instead of `external_module/helpers.py` to have `tests/steps/given.py`, ``tests/steps/then.py`, ``tests/steps/when.py`. Then in `tests/conftest.py` have 
```
from .steps.then import *
```
etc
check paylogic best practices as well: http://developer.paylogic.com/articles/how-we-use-pytest-and-pytest-bdd-in-paylogic.html

**Comment by tanzeel-bhatti** [comment]
@bubenkoff  Is there a way I can import common steps from a common module and use them in different scenarios/modules. There is also a question on Stack Overflow but no one answered.

https://stackoverflow.com/questions/52265620/pytest-bdd-importing-common-steps

**Comment by Drachenfels** [comment]
I second this request. Importing wildcard is considered somewhat anti-pattern nowadays.
