### ISSUE TITLE
pytest 3.8 generates warnings about directly calling fixtures

### ISSUE THREAD

**Issue by okken** [pytest-dev/pytest-bdd#253]
This rather unfortunately confusing warning occurs with pytest 3.8:

```
============= warnings summary =================
<path>\venv\lib\site-packages\pytest_bdd\scenario.py:228:\
RemovedInPytest4Warning: Fixture "pytestbdd_feature_base_dir" called directly. \
Fixtures are not meant to be called directly, are created automatically when test functions\
request them as parameters. \
See https://docs.pytest.org/en/latest/fixture.html for more information.\
  return call_fixture(getattr(fixtures, fixture))

<path>\venv\lib\site-packages\pytest_bdd\scenario.py:228: \
RemovedInPytest4Warning: Fixture "pytestbdd_strict_gherkin" called directly. \
Fixtures are not meant to be called directly, are created automatically when test functions \
request them as parameters. \
See https://docs.pytest.org/en/latest/fixture.html for more information.
  return call_fixture(getattr(fixtures, fixture))
```

Simple test file for playing with pytest-bdd:

try.feature:
```
Feature: One

  Scenario: First scenario
    Given some state
    When something happens
    Then result should occur
```

test_try.py:
```
from pytest_bdd import scenario, given, when, then

@scenario('try.feature', 'First scenario')
def test_first_scenario():
    pass

@given("some state")
def some_state():
    pass

@when("something happens")
def something_happens():
    pass

@then("result should occur")
def result_should_occur():
    pass
```

**Comment by youtux** [comment]
pytest_bdd is indeed calling a fixture function, and this behavior is now deprecated by pytest and it will be removed in pytest 4.
It will require a major rewrite of pytest_bdd, PRs are welcome.

**Comment by The-Compiler** [comment]
This seemed to work:

```diff
commit a0d65434d730777f9d6477bd4b748b558bb9fdf6
Author: Florian Bruhin <me@the-compiler.org>
Date:   Fri Sep 7 20:54:43 2018 +0200

    Work around pytest's warning for calling fixture functions
    
    pytest 3.7.0 introduced a warning when fixture functions are called directly.
    We do want to do that without triggering the warning, so we need to unwrap it.

diff --git a/pytest_bdd/scenario.py b/pytest_bdd/scenario.py
index f5b141b..45084e9 100644
--- a/pytest_bdd/scenario.py
+++ b/pytest_bdd/scenario.py
@@ -207,6 +207,9 @@ FakeRequest = collections.namedtuple("FakeRequest", ["module"])
 def get_fixture(caller_module, fixture, path=None):
     """Get first conftest module from given one."""
     def call_fixture(function):
+        if hasattr(function, '__pytest_wrapped__'):
+            function = function.__pytest_wrapped__.obj
+
         args = []
         if "request" in get_args(function):
             args = [FakeRequest(module=caller_module)]
```

but I got lost after that trying to fix #250.

**Comment by youtux** [comment]
@The-Compiler this approach uses even more internals of pytest that could break anytime, so I am not really sure about using this solution.

**Comment by hakkeroid** [comment]
> This seemed to work:
> 
> ```diff
> commit a0d65434d730777f9d6477bd4b748b558bb9fdf6
> Author: Florian Bruhin <me@the-compiler.org>
> Date:   Fri Sep 7 20:54:43 2018 +0200
> 
>     Work around pytest's warning for calling fixture functions
>     
>     pytest 3.7.0 introduced a warning when fixture functions are called directly.
>     We do want to do that without triggering the warning, so we need to unwrap it.
> 
> diff --git a/pytest_bdd/scenario.py b/pytest_bdd/scenario.py
> index f5b141b..45084e9 100644
> --- a/pytest_bdd/scenario.py
> +++ b/pytest_bdd/scenario.py
> @@ -207,6 +207,9 @@ FakeRequest = collections.namedtuple("FakeRequest", ["module"])
>  def get_fixture(caller_module, fixture, path=None):
>      """Get first conftest module from given one."""
>      def call_fixture(function):
> +        if hasattr(function, '__pytest_wrapped__'):
> +            function = function.__pytest_wrapped__.obj
> +
>          args = []
>          if "request" in get_args(function):
>              args = [FakeRequest(module=caller_module)]
> ```
> 
> but I got lost after that trying to fix #250.

The next broken part is that pytest-bdd asks pytest for a fixture with the actual text from the feature file. However, in the pytest fixture manager the step functions are stored with the parametrized text. Because of that the feature is not found in the first run. In the next round pytest-bdd goes through all known pytest fixtures and tries to find a parser on it. That way it can generate the unparametrized text and ask pytest again. [This part is broken](https://github.com/pytest-dev/pytest-bdd/blob/fb2840391ffe22cab9b3d78454bbafd64962c535/pytest_bdd/scenario.py#L62).
```python
# scenario.py
for fixturename, fixturedefs in list(fixturemanager._arg2fixturedefs.items()):
    for fixturedef in fixturedefs:
        parser = getattr(fixturedef.func, "parser", None)  # offending line
```
The issue is that pytest-bdd adds the parser [to the function object](https://github.com/pytest-dev/pytest-bdd/blob/fb2840391ffe22cab9b3d78454bbafd64962c535/pytest_bdd/steps.py#L189) when parsing the test files initially.
```python
# steps.py
step_func.parser = lazy_step_func.parser = parser_instance
```
It seems that because of the changed `_arg2fixturedefs` the fixture function does not host the assigned parser anymore when it is retrieved from the pytest fixturemanager.

**Comment by youtux** [comment]
I made a kind of working implementation that removes the use of `pytestbdd_feature_base_dir` and `pytestbdd_strict_gherkin` altogether, since fixtures are not meant to be evaluated at import time anyway.
The only problem is that the change is not backwards compatible, but the migration is quite simple: 

- instead of defining a `pytestbdd_feature_base_dir` fixture, you have to set the base_path from an environment variable `PYTEST_BDD_BASE_PATH` (we can even avoid this by traversing the directories up to the root and looking for the feature file, we'll see). For instance, you can invoke pytest like this:
`$ PYTEST_BDD_BASE_PATH=$(PWD)/features pytest tests/`

- instead of defining a `pytestbdd_strict_gherkin`, just pass a new parameter to the `scenario` or `scenarios` function:
`scenarios('foo/bar.feature', strict_gherkin=True)`

Here's the branch I'm working on, in case anybody is interested: https://github.com/paylogic/pytest-bdd/tree/remove-pytestbdd-fixtures

**Comment by sliwinski-milosz** [comment]
I think the correct approach is to make user able to set both: `pytestbdd_feature_base_dir` and `pytestbdd_strict_gherkin` in any of three below ways:
1. By setting it in pytest.ini configuration file
2. By environment variable
3. By command line argument

The same way as it is done for `pytest-django` and its [settings module](https://pytest-django.readthedocs.io/en/latest/tutorial.html#step-2-point-pytest-to-your-django-settings)

Possibility to pass above parameters to `scenario` and `scenarios` function may be also nice feature.

**Comment by The-Compiler** [comment]
FWIW I don't think it should be the plugin's responsibility to look in many different places. IMHO, the proper place for this would be the config file.

pytest already has `-o` which lets you set config file settings from the commandline, and `PYTEST_ADDOPTS` which lets you do so via an environment variable. No need to duplicate all that logic in every plugin.

**Comment by youtux** [comment]
The problem is that feature files are being read at import time, and at
import time you have no access to pytest’s `request.config` object.
