### ISSUE TITLE
Generate py.test code and fixtures from .feature files

### ISSUE THREAD

**Issue by prologic** [pytest-dev/pytest-bdd#32]
It would be nice if py.test_bdd provided a cli tool to automatically generate the necessary structures from `.feature` file(s). I think I would find it painful to have to reproduce the contents of `.feature` files in my tests.

**Comment by evbo** [comment]
@bubenkoff I'm curious what not support the other direction?: from pytest tests code file generate `feature` file? Consider a very common case:

product owner isn't a developer and so of course the feature file they write misses some key corner cases. The developer is diligent and adds tests for these corner cases, but of course needs to update the `.feature` file.

Currently the developer has to auto-generate another test file, copy their previous implementations in, etc. If instead we generated the `.feature` file automatically, since it's just an interface with no implementation, it's so much easier to sync.

I get that product owner should own `.feature` file ideally, but realistically it is often a 2-way street and developer should be able to make changes automatically.
