### ISSUE TITLE
Bug: TestClass methods are not supported by @scenario

### ISSUE THREAD

**Issue by daihaminkey** [pytest-dev/pytest-bdd#325]
If you place test function in class and add `self` arg to it, `@scenario` decorator will try to find fixture 'self', which is obviously doesn't exists.

Bug found in 3.2.1, but I suppose it cames from 3.2.0 update.

![изображение](https://user-images.githubusercontent.com/39711756/64245315-5cd06400-cf13-11e9-8ecf-67f1cbddf1d2.png)

**Comment by youtux** [comment]
Hi @daihaminkey thanks for the bug report! Can you check if it was working before 3.2.0?

**Comment by youtux** [comment]
Indeed this comes with the 3.2.0 update.
I gave it a look, but I cannot find an easy fix for your situation. A workaround is to just split scenarios in multiple python modules, instead of multiple classes.
Also, I cannot find any reference in the documentation nor a test about having `@scenario` calls inside a TestClass, so I guess that pytest_bdd was never written with that in mind; it just so happened to be working.

Possibly, one day pytest_bdd will generate test items from feature files directly, without having to write any python test module. Only step definitions will be required of course. If that will happen, then this use case of having scenarios inside test classes will not be possible at all.
