### ISSUE TITLE
@given with target_fixture does not behave like pytest-fixture on yield anymore

### ISSUE THREAD

**Issue by raspe88** [pytest-dev/pytest-bdd#392]
In v4.0.1 "given"-steps with "target_fixture" being set do no longer behave the same way pytest-fixtures do when a value is yielded. This is either a not explicitly documented change in the behaviour since 3.4.0 or a bug.

When using such a "given"-step, I do no longer get the yielded value (as I would expect from a pytest-fixture), but a generator. This is a hindrance for e.g. using context managers within a given-step that ensure that something will be cleaned up at the end of a test case.

Let me give you one example:

```py
@given("a running server", target_fixture="running_server")
def run_server():
    with subprocess.Popen("./start_my_server",  stdout=subprocess.PIPE) as proc:
        yield proc

@when("I do something")
def do_something():
   # e.g. send some request to the server

@then("the server does something")
def the_server_does_something(running_server):
    assert running_server.stdout.read() == "some kind of information"
    # running_server now is a generator in v4.0.1 but has been a subprocess.Popen in 3.4.0
```

**Comment by youtux** [comment]
It was just a side effect of the old implementation, this behavior was never documented.
I would suggest you make your own decorator that transforms a generator step function to a non-generator test function.
It could be something like this:

```python
import functools
import inspect

def yield_step(f):
    @functools.wraps(f)
    def wrapper(request, *args, **kwargs):
        gen = f(*args, **kwargs)
        
        request.addfinalizer(lambda: next(gen))

        return next(gen)
    
    # Add the parameter "request" to the signature of the wrapper function, so that it will be injected
    sig = inspect.signature(f)
    request_param = inspect.Parameter('request', kind=inspect.Parameter.POSITIONAL_OR_KEYWORD)
    sig = sig.replace(parameters=list(sig.parameters.values()) + [request_param])
    wrapper.__signature__ = sig

    return wrapper

@given("a running server", target_fixture="running_server")
@yield_step
def run_server():
    with subprocess.Popen("./start_my_server",  stdout=subprocess.PIPE) as proc:
        yield proc

```

**Comment by youtux** [comment]
Another approach is to define your `run_server` as a normal fixture, and then require that fixture in your step definition:

```python3
@pytest.fixture
def runing_server():
    with subprocess.Popen("./start_my_server",  stdout=subprocess.PIPE) as proc:
        yield proc

@given("there is a running server")
def there_is_a_running_server(running_server):
    pass
```

**Comment by raspe88** [comment]
But wouldn't it be nice if the pytest-bdd "target_fixture" does behave like a real pytest-fixture? The documentation may imply this. Using a workaround is possible but e.g. your the second suggestion (I actually do this at the moment) makes it harder to see the workflow? Based on the first workaround suggested by you it feels like something that can be put directly into pytest-bdd.

**Comment by jamesharris-garmin** [comment]
it would be nice if the (switch to a feature) method were explained in the migrating from 3.x section. I understand it is undocumented behavior.

**Comment by crazy-eddie** [comment]
I would like to argue for this being a defect.  Perhaps it's undocumented, but in pytest it IS documented to work this way...making the expected behavior quite natural for a pytest library.  The suggested code works with some tweaks, but I found the fact that it didn't work like pytest in general quite surprising and having to use a hack for the natural behavior seems undesirable.  I would expect a pytest library to document EXCEPTIONS to how the pytest environment works, not add them later because THIS library wasn't documented to behave that way.

I don't know why the change that caused this, but I think it deserves some real attention that its expected to behave a certain way and just doesn't.

**Comment by MLNW** [comment]
I just stumbled over this and have spent quite some time figuring out that `yield` does not work as expected when using it with `pytest-bdd` fixtures.

Please think about adding that as a feature since it would make writing clean-up for tests straightforward and in line with general `pytest` best practices.
