### ISSUE TITLE
need to pass variable to pytest_bdd_step_error hook, is it possible?

### ISSUE THREAD

**Issue by magowiz** [pytest-dev/pytest-bdd#443]
Hi,
I'm developing, using pytest_bdd and selenium, some tests on a web application, what I would like to do is that, on step failure, current instance of driver (implemented by Firefox) gets closed before next test, so I would like to know if there is a way I can pass the driver object to `pytest_bdd_step_error` hook, so I can call `driver.quit()` or if across default arguments I can retrieve it.
I don't know if I am using right method to accomplish this, please also tell me if there is a way also not using hooks.

Best regards,
magowiz

**Comment by jsa34** [comment]
I am assuming that you are creating the webdriver object in a fixture.

The best way to do the above behaviour is to make the webdriver be yielded, and then it will call quit() at the end of the test, regardless of whether it passes or fails.

For example:

```
@pytest.fixture
def driver():
    driver = webdriver.Chrome(options=options)
    yield driver
    driver.quit()
```

Then you can use the `driver` arg in your steps, and at the end of the test scope (whether it passes or fails), it will call any methods after the `yield` statement (in this case, `driver.quit()`).

I hope this answers your question, @magowiz !

If I don't hear back in a few days (as it's been a while since this was reported), I will consider this issue closed.

**Comment by jsa34** [comment]
Please feel free to reopen based on my last comment @magowiz if necessary
