### ISSUE TITLE
Exception: gherkin-terminal-reporter is not compatible with 'xdist' plugin. 

### ISSUE THREAD

**Issue by ed-sparkes** [pytest-dev/pytest-bdd#501]
Hi, 

I am getting the error Exception: gherkin-terminal-reporter is not compatible with 'xdist' plugin.

I am on M1 Macbook running Python 3.9.5

Colleague on non apple silicon are not seeing this error.

Any thoughts? 

Kind regards

**Comment by youtux** [comment]
Hi, can you provide more info? For example, it would be great to know how you invoke pytest, which options you use (both in the command line and from config files).

I suspect that you are using the gherkin-terminal-reporter option together with the pytest-xdist, which is not compatible (as the message says).

**Comment by musicinmybrain** [comment]
Interestingly, I’m hitting this in the RPM build environment while updating the Fedora Rawhide package to jrnl 6.0, using the new `tox` configuration in a straightforward way. This is with:

- poetry-core 1.0.8
- pip 22.0.4
- tox 3.25.0
- pytest 7.1.2
- pytest-bdd 5.0.0
- pytest-xdist 2.5.0
- toml 0.10.2

It makes sense that this happens, since `addopts` in `[tool.pytest.ini_options]` contains both `"--gherkin-terminal-reporter"` and `"-n=auto"`. The only thing that surprises me is that this isn’t happening for *everyone*.

The only obvious fix I could find was patching out one option or the other in `pyproject.toml`. I chose to patch out `"--gherkin-terminal-reporter"`.

**Comment by youtux** [comment]
I use apple silicon as well, and I don't see this error. Would you able to provide a minimal example that triggers this error?

**Comment by musicinmybrain** [comment]
> I use apple silicon as well, and I don't see this error. Would you able to provide a minimal example that triggers this error?

I think I commented on this issue without noticing I had followed a link to an issue on this project. I believe the problem I was encountering is downstream in `jrnl`.

**Comment by GuyGrinwald** [comment]
> Hi, can you provide more info? For example, it would be great to know how you invoke pytest, which options you use (both in the command line and from config files).
> 
> I suspect that you are using the gherkin-terminal-reporter option together with the pytest-xdist, which is not compatible (as the message says).

@youtux are there any plans to support `pytest-xdist` with the `gherkin-terminal-reporter` or can you explain the motivation of why this isn't supported? I've also encountered a situation where `pytest -m my-tag --gherkin-terminal-reporter --gherkin-terminal-reporter-expanded -s --no-success-flaky-report --force-flaky --tb=native` works well on ubuntu but not on macOS. I'm running, `pytest==6.2.5, pytest-bdd==4.1.0, pytest-xdist==3.1.0`

**Comment by youtux** [comment]
That's quite an old version of pytest-bdd.
Anyway, I can't remember on top of my head why two options are not compatible
